name: Feature Request Form
description: Create a new ticket for a new feature request
title: "Request for [feature]"
labels: ["enhancement","question"]
assignees:
  - Tilliforkids
  - mynap
body:
  - type: textarea
    id: drawbacks
    attributes:
      label: "Drawbacks"
      description: What are the drawbacks/impacts of your feature request ?
      placeholder: Identify the drawbacks and impacts while being neutral on your feature request
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: "Background"
      description: Share context as to why this new feature is important or why it should be completed.
      Placeholder: This feature is important because…
      required: true
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What questions still remain unresolved ?
      placeholder: Identify any unresolved issues.
    validations:
      required: false
